Develop
Gods-Of-ACM/frontEnd pull request #28
Opened 2018-04-01 22:39 UTC by bsonge

Merging base develop with master branch.  This should be the "v1" of the project that we showed off in class.  I'd like to go ahead and update master before we move on.

2018-04-01 23:01 UTC, Quinn-Donnelly commented
What is the status on the test cases for the components we have built so far?

2018-04-01 23:04 UTC, Quinn-Donnelly commented on app/components/BigBtn1/index.js
> +BigBtn1.propTypes = {
Unsure how this component is being used however I think a few more props are probably required.

2018-04-01 23:05 UTC, Quinn-Donnelly commented on app/components/BigBtn1/tests/index.test.js
> +  it('Expect to have unit tests specified', () => {
I will also post once by the tests I think we should write some before we go onto to other work or merge to master.

2018-04-01 23:06 UTC, Quinn-Donnelly commented on app/components/Button1/index.js
> +  // isBtnActive = () => {
If we aren't using this commented code we should purge it for clean code.

2018-04-01 23:07 UTC, Quinn-Donnelly commented on app/components/Button1/messages.js
> +    defaultMessage: 'CLIK MEE',
Careful with our messages being informal (flashback to phase one report)

2018-04-01 23:50 UTC, Quinn-Donnelly requested changes
I have reviewed the changes and comments on the files where I found thinks that might need to be changed. If it was a reoccurring change that needed to be made I only commented once about it but it could appear in multiple locations.

2018-04-01 23:50 UTC, Quinn-Donnelly commented on app/components/DbEntry/index.js
> +  minmax(evt) {
Not sure which naming convention we are using for function names but we should decide on one. Also the fill function seems to be useless in it's current state.

2018-04-01 23:50 UTC, Quinn-Donnelly commented on app/components/DbEntry/index.js
> +    // const open = {
Same as above vestigial code should either be removed or commented to explain what it is there for.

2018-04-01 23:50 UTC, Quinn-Donnelly commented on app/containers/HomePage/index.js
> +          <BigBtn1 tab="1%" theme={theme} text="View Database" link="/database" handler={(link) => this.navigate(link)} />
If we are linking in this manner then it is especially important that we write test cases to verify these links so we don't forget about them when we make changes to their respective pages.

2018-04-01 23:50 UTC, Quinn-Donnelly commented on app/containers/NavBar/index.js
> +        <Button1 theme={theme} text="HOME" link="/" handler={(link) => this.navigate(link)} />
These will be important to have tests for to check unverified links.

2018-04-01 23:50 UTC, Quinn-Donnelly commented on app/containers/Registration/index.js
> +        <PageHeader title="Registration" />
For text the messages file should be used so that we can use the Language Provider.

2018-04-01 23:50 UTC, Quinn-Donnelly commented on test_html/button1.html
> +/*
Not sure what this file or directory are being used for.

2018-04-02 21:18 UTC, bsonge commented
I'll review the changes and get fixes going.  We started test cases yesterday and realized that if we do only test cases we might not get enough time to actually implement phase II, so I think the consensus is to start on phase II changes and write tests as we go so that we get used to it, then co back if we have time.

2018-04-05 03:50 UTC, closed without merging